# Generated by Django 3.0.5 on 2020-08-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20200801_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Manager.Seller'),
        ),
    ]
