# Generated by Django 3.0.5 on 2020-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20200804_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='res_pics/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wechatcode',
            field=models.ImageField(blank=True, default='', null=True, upload_to='wechat_code/'),
        ),
    ]
