# Generated by Django 3.0.5 on 2020-08-02 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manager', '0003_auto_20200801_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, default='static/Manager/images/defaultimage.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
