# Generated by Django 3.0.5 on 2020-08-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20200802_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='media/defaultimage.jpg', upload_to='dish_images/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, default='media/defaultimage.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
