# Generated by Django 3.0.5 on 2020-08-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20200804_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Manager.Kind'),
        ),
    ]
