# Generated by Django 3.0.5 on 2020-08-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_auto_20200805_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='detail',
        ),
    ]
