# Generated by Django 3.0.5 on 2020-08-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_auto_20200805_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
