# Generated by Django 3.0.5 on 2020-08-15 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0010_order_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_num',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
