# Generated by Django 3.0.5 on 2020-08-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0012_auto_20200816_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
