# Generated by Django 3.0.5 on 2020-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0015_auto_20200818_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CNY_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
